#!/usr/bin/env python3
"""Generates kernel/src/drivers/font_8x16.ign from the Spleen 8x16 BDF font.

Usage: scripts/gen-font.py <spleen-8x16.bdf> <output.ign>

Inside `nix develop`, the BDF file is at "$SPLEEN_DIR/spleen-8x16.bdf".
The output holds one 16-byte glyph per character from FIRST to LAST, one byte
per row, most significant bit on the left. The table is an array literal with
one glyph of 16 values per line and a trailing comma, a layout `ignis fmt`
keeps as is.
"""

import sys

FIRST = 0x20
LAST = 0x7E
WIDTH = 8
HEIGHT = 16

# Template of the generated file. The doc comments in it are part of the output,
# so a change here has to be followed by `make font`.
HEADER = """\
//! Glyphs 0x{first:02X}-0x{last:02X} of the Spleen {version} 8x16 bitmap font,
//! generated by scripts/gen-font.py from spleen-8x16.bdf. Do not edit by hand.
//!
//! Spleen: https://github.com/fcambus/spleen
//! Copyright (c) 2018-2026, Frederic Cambus
//! Released under the BSD 2-Clause license. The full text is in
//! LICENSES/Spleen-BSD-2-Clause.txt.
//! SPDX-License-Identifier: BSD-2-Clause
//!
//! Each glyph is {height} bytes, one per row from the top, with the most
//! significant bit as the leftmost pixel. kernel/src/drivers/font.ign reads them.

/// Holder of the generated glyph table.
namespace Drivers::FontData {{
  /// Record that owns the table as a public static array.
  record Glyphs {{
    /// {count} glyphs of {height} bytes each, in character order from 0x{first:02X}.
    /// Glyph `c` starts at byte `(c - 0x{first:02X}) * {height}`. Row 0 is the top row
    /// and bit 7 of a row byte is the leftmost pixel.
    public static rows: u8[{size}] = [
{rows}
    ];
  }}
}}
"""


def parse_bdf(path):
    """Returns the font version and a map from code point to row bytes.

    A BDF glyph is a block of lines: ENCODING gives the code point, BBX the
    bounding box (width, height, x offset, y offset), BITMAP starts one hex
    byte per row, top row first, and ENDCHAR closes the glyph. Spleen 8x16
    glyphs are 8 wide, so each row is exactly one byte.
    """
    version = "unknown"
    glyphs = {}
    encoding = None
    rows = None

    with open(path, encoding="ascii") as bdf:
        for raw_line in bdf:
            line = raw_line.strip()

            if line.startswith("FONT_VERSION "):
                version = line.split(" ", 1)[1].strip('"')
            elif line.startswith("ENCODING "):
                encoding = int(line.split()[1])
            elif line.startswith("BBX "):
                width, height, x_offset, y_offset = (int(field) for field in line.split()[1:])

                # y offset -4 is the descender line of Spleen 8x16. A glyph with
                # another box would not fit the fixed 8x16 cell.
                if (width, height, x_offset, y_offset) != (WIDTH, HEIGHT, 0, -4):
                    sys.exit(f"glyph {encoding}: unexpected bounding box {line}")
            elif line == "BITMAP":
                rows = []
            elif line == "ENDCHAR":
                glyphs[encoding] = rows
                encoding = None
                rows = None
            elif rows is not None:
                rows.append(int(line, 16))

    return version, glyphs


def main():
    """Reads the BDF named first and writes the Ignis table to the second path."""
    if len(sys.argv) != 3:
        sys.exit(__doc__)

    version, glyphs = parse_bdf(sys.argv[1])
    rows = []

    for code in range(FIRST, LAST + 1):
        glyph = glyphs.get(code)

        if glyph is None or len(glyph) != HEIGHT:
            sys.exit(f"glyph 0x{code:02X} is missing or not {HEIGHT} rows high")

        rows.append(", ".join(f"0x{row:02X}" for row in glyph) + ",")

    text = HEADER.format(
        first=FIRST,
        last=LAST,
        version=version,
        height=HEIGHT,
        count=len(rows),
        size=len(rows) * HEIGHT,
        rows="\n".join(f"      {line}" for line in rows),
    )

    with open(sys.argv[2], "w", encoding="ascii") as output:
        output.write(text)


if __name__ == "__main__":
    main()
