#!/usr/bin/env python3
"""Generates kernel/src/font_8x16.ign from the Spleen 8x16 BDF font.

Usage: scripts/gen-font.py <spleen-8x16.bdf> <output.ign>

Inside `nix develop`, the BDF file is at "$SPLEEN_DIR/spleen-8x16.bdf".
The output holds one 16-byte glyph per character from FIRST to LAST, one byte
per row, most significant bit on the left. The table is a single array
literal on one line, the layout `ignis fmt` produces for it.
"""

import sys

FIRST = 0x20
LAST = 0x7E
WIDTH = 8
HEIGHT = 16

HEADER = """\
//! Glyphs 0x{first:02X}-0x{last:02X} of the Spleen {version} 8x16 bitmap font,
//! generated by scripts/gen-font.py from spleen-8x16.bdf. Do not edit by hand.
//!
//! Spleen: https://github.com/fcambus/spleen
//! Copyright (c) 2018-2026, Frederic Cambus
//! Released under the BSD 2-Clause license. The full text is in
//! LICENSES/Spleen-BSD-2-Clause.txt.
//! SPDX-License-Identifier: BSD-2-Clause
//!
//! Each glyph is {height} bytes, one per row from the top, with the most
//! significant bit as the leftmost pixel. kernel/src/font.ign reads them.

export namespace FontData {{
  record Glyphs {{
    /// `static mut` because only a mutable static is emitted as one global
    /// whose address stays valid. Nothing writes to it.
    public static mut rows: u8[{size}] = [{rows}];
  }}
}}
"""


def parse_bdf(path):
    """Returns the font version and a map from code point to row bytes."""
    version = "unknown"
    glyphs = {}
    encoding = None
    rows = None

    with open(path, encoding="ascii") as bdf:
        for raw_line in bdf:
            line = raw_line.strip()

            if line.startswith("FONT_VERSION "):
                version = line.split(" ", 1)[1].strip('"')
            elif line.startswith("ENCODING "):
                encoding = int(line.split()[1])
            elif line.startswith("BBX "):
                width, height, x_offset, y_offset = (int(field) for field in line.split()[1:])

                if (width, height, x_offset, y_offset) != (WIDTH, HEIGHT, 0, -4):
                    sys.exit(f"glyph {encoding}: unexpected bounding box {line}")
            elif line == "BITMAP":
                rows = []
            elif line == "ENDCHAR":
                glyphs[encoding] = rows
                encoding = None
                rows = None
            elif rows is not None:
                rows.append(int(line, 16))

    return version, glyphs


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)

    version, glyphs = parse_bdf(sys.argv[1])
    rows = []

    for code in range(FIRST, LAST + 1):
        glyph = glyphs.get(code)

        if glyph is None or len(glyph) != HEIGHT:
            sys.exit(f"glyph 0x{code:02X} is missing or not {HEIGHT} rows high")

        rows.extend(f"0x{row:02X}" for row in glyph)

    text = HEADER.format(
        first=FIRST,
        last=LAST,
        version=version,
        height=HEIGHT,
        size=len(rows),
        rows=", ".join(rows),
    )

    with open(sys.argv[2], "w", encoding="ascii") as output:
        output.write(text)


if __name__ == "__main__":
    main()
